# Checking pytorch

With and without GPU. GPU access is currently only possible on Intel based machines with NVIDIA GPUs

In [1]:
import torch

# Check if CUDA (GPU) is available
print(f"CUDA is available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Current GPU device: {torch.cuda.get_device_name()}")

# Create a sample tensor
cpu_tensor = torch.randn(3, 3)
print("\nCPU Tensor:")
print(cpu_tensor)

# Move tensor to GPU if available
if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.cuda()
    print("\nGPU Tensor:")
    print(gpu_tensor)

# Basic operation example
result = cpu_tensor.matmul(cpu_tensor)
print("\nMatrix multiplication result (CPU):")
print(result)

CUDA is available: True
Current GPU device: NVIDIA A16

CPU Tensor:
tensor([[ 0.1179,  0.1374, -1.1238],
        [-0.7767, -0.5810, -0.4733],
        [-0.9841,  0.2147,  0.1074]])

GPU Tensor:
tensor([[ 0.1179,  0.1374, -1.1238],
        [-0.7767, -0.5810, -0.4733],
        [-0.9841,  0.2147,  0.1074]], device='cuda:0')

Matrix multiplication result (CPU):
tensor([[ 1.0131, -0.3049, -0.3183],
        [ 0.8254,  0.1292,  1.0969],
        [-0.3885, -0.2368,  1.0158]])


In [2]:
import torch

print(f"CUDA version: {torch.version.cuda}")
print(f"Available devices: {torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"Current device: {torch.cuda.get_device_name()}")

CUDA version: 12.6
Available devices: 1
Current device: NVIDIA A16


In [3]:
# nvidia-ctk --version
# nvidia-container-cli --version
# nvidia-smi

Seems we have the following on the host system:

* GPU: NVIDIA A16
* Container toolkit version: 1.17.4
* NVIDIA-SMI 570.86.10
* Driver Version: 570.86.10
* CUDA Version: 12.8

In [4]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

if torch.cuda.is_available():
    print(f"Current device: {torch.cuda.get_device_name()}")
    # Try a simple CUDA operation
    x = torch.rand(3,3).cuda()
    print("CUDA tensor created successfully:", x)

PyTorch version: 2.6.0+cu126
CUDA available: True
CUDA version: 12.6
Current device: NVIDIA A16
CUDA tensor created successfully: tensor([[0.3801, 0.6089, 0.2225],
        [0.1539, 0.8502, 0.2112],
        [0.8333, 0.7343, 0.6278]], device='cuda:0')


In [5]:
torch.__file__

'/opt/conda/lib/python3.12/site-packages/torch/__init__.py'