# Checking pytorch

With and without GPU. GPU access is currently only possible on Intel based machines with NVIDIA GPUs

In [1]:
import torch

# Check if CUDA (GPU) is available
print(f"CUDA is available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Current GPU device: {torch.cuda.get_device_name()}")

# Create a sample tensor
cpu_tensor = torch.randn(3, 3)
print("\nCPU Tensor:")
print(cpu_tensor)

# Move tensor to GPU if available
if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.cuda()
    print("\nGPU Tensor:")
    print(gpu_tensor)

# Basic operation example
result = cpu_tensor.matmul(cpu_tensor)
print("\nMatrix multiplication result (CPU):")
print(result)

CUDA is available: True
Current GPU device: NVIDIA A16

CPU Tensor:
tensor([[-0.6716,  1.1265,  0.7818],
        [ 2.1351, -0.1726,  0.8595],
        [-0.0103,  0.0392,  1.1856]])

GPU Tensor:
tensor([[-0.6716,  1.1265,  0.7818],
        [ 2.1351, -0.1726,  0.8595],
        [-0.0103,  0.0392,  1.1856]], device='cuda:0')

Matrix multiplication result (CPU):
tensor([[ 2.8481, -0.9203,  1.3701],
        [-1.8113,  2.4687,  2.5399],
        [ 0.0784,  0.0281,  1.4313]])


In [2]:
import torch
print(f"CUDA version: {torch.version.cuda}")
print(f"Available devices: {torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"Current device: {torch.cuda.get_device_name()}")

CUDA version: 12.6
Available devices: 8
Current device: NVIDIA A16


In [3]:
# nvidia-ctk --version
# nvidia-container-cli --version

# seems we have
CUDA version: 12.4
GPU: NVIDIA A16
Container toolkit version: 1.17.4

In [4]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")

if torch.cuda.is_available():
    print(f"Current device: {torch.cuda.get_device_name()}")
    # Try a simple CUDA operation
    x = torch.rand(3,3).cuda()
    print("CUDA tensor created successfully:", x)

PyTorch version: 2.6.0+cu126
CUDA available: True
CUDA version: 12.6
Current device: NVIDIA A16
CUDA tensor created successfully: tensor([[0.9373, 0.1667, 0.7268],
        [0.0199, 0.2263, 0.8252],
        [0.7975, 0.4041, 0.4180]], device='cuda:0')
